name: Go CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.2']
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Build
        run: go build -v ./.
      
      - name: Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./.
          go tool cover -func=coverage.txt
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
      
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout 5m